### ISSUE TITLE
unexpected make build result

### ISSUE THREAD

**Issue by coolbed** [CECTC/dbpack#119]
As described  in the [[compile section](https://cectc.github.io/dbpack-doc/#/getting_started?id=%e7%bc%96%e8%af%91)](https://cectc.github.io/dbpack-doc/#/getting_started?id=%e7%bc%96%e8%af%91) of getting started doc, a binary file is expected to be built in the dist directory when **make build** executed. When i run **make build** on my MacBook, a binary file is built in the project root directory and the file can not be executed because of an exec format error. I check the makefile and find the build doesn't work as it's expected to.

```makefile
build:  ## build dbpack cli, and put in dist dir
	GOOS="linux"  GOARCH="amd64" CGO_ENABLED=0 go build -o dbpack ./cmd
```

**Comment by dk-lockdown** [comment]
you should run `make build-local`, i will update the doc immediately.

**Comment by coolbed** [comment]
Yeah, i found build-local in makefile. Many thanks for the prompt reply.
