### ISSUE TITLE
unit test for `pkg/misc/escape.go`

### ISSUE THREAD

**Issue by dk-lockdown** [CECTC/dbpack#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tanryberdi** [comment]
@dk-lockdown I think this task is done, am i right?

**Comment by dk-lockdown** [comment]
yes，it is，you can do another task

**Comment by tanryberdi** [comment]
> yes，it is，you can do another task
could you please close this issue? I will jump to #68
