### ISSUE TITLE
unit test for `pkg/misc/time.go`

### ISSUE THREAD

**Issue by dk-lockdown** [CECTC/dbpack#70]
**Is your feature request related to a problem? Please describe.**

test func `func FormatTimeMillis(tsMillis uint64) string ` and func `func FormatDate(tsMillis uint64) string`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tanryberdi** [comment]
Hey guys, this one is merged, and when i want to `git pull` from `dev` branch, i could not get last updates for unit test for `FormatTimeMillis`, what is my bad? how could i `git pull` dev branch to last version to continue with other unit test issues

**Comment by dk-lockdown** [comment]
you can fetch upstream, follow these steps:
```
git remote add upstream  git@github.com:cectc/dbpack.git
git fetch upstream
git pull --rebase upstream dev
git push -f
```
