### ISSUE TITLE
test: unit test for `pkg/filter/dt/executor.go`

### ISSUE THREAD

**Issue by dk-lockdown** [CECTC/dbpack#95]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dk-lockdown** [comment]
This file has been refactored into several smaller files, they are `pkg/filter/dt/exec/prepare_delete.go`、`pkg/filter/dt/exec/prepare_insert.go`、`pkg/filter/dt/exec/prepare_update.go`. refer to https://github.com/CECTC/dbpack/pull/107

**Comment by tanryberdi** [comment]
then, i will wait for merging #107 , after that, i will request one more time for refactored one

**Comment by dk-lockdown** [comment]
https://github.com/CECTC/dbpack/pull/107 has merged, you can work with it

**Comment by dk-lockdown** [comment]
@tanryberdi are you working with this issue?

**Comment by tanryberdi** [comment]
> @tanryberdi are you working with this issue?

For now, no, but let me investigate
